### ISSUE TITLE
Add 5-Yard Range Check

### ISSUE THREAD

**Issue by Pixolsc2** [DeadlyBossMods/DBM-TBC-Classic#104]
**Is your feature request related to a problem? Please describe.**
Add 5-yard Range Check to DBM-TBC-Classic. Useful for fights like Illidan Black Temple where 5 yard range spread is recommended:
https://wowpedia.fandom.com/wiki/Illidan_Stormrage_(tactics)
Flame Burst / Agonizing Flames

Currently DBM still has code that attempts to use 6-yard range check for Illidan, but I don't think it works for TBC client. So people are using 8yards instead.

**Describe the solution you'd like**
Add this item as a 5-yard item range check:
https://tbc.wowhead.com/item=16114/foremans-blackjack

**Describe alternatives you've considered**
Alternative item that seems to function the same:
https://tbc.wowhead.com/item=30251/rinas-diminution-powder

**Additional context**
Items were verified to be 5.0yards on party members when compared with UnitDistanceSquared for the following characters:
 - Female Dwarf and Female Human
 - Female Bloodelf and Female Bloodelf

Male Tauren and Female Bloodelf seem to be closer to 7yards, but I think Tauren hitboxes affect all the item ranges in general so it's to be expected..?

Items were found by scanning item IDs ranging from 1-40000

Note: Not tested on Illidan Encounter

**Comment by MysticalOS** [comment]
i'll verify those ranges in game using apis and at very least get foremans backpack to re-enable 6 yards in tbc if my findings are the same.

 the reason none of the 5 yard items are used for 5 yards is because in just about any case tested spell splash occurs. I bet it'll work well as a safe 6 yard range check though. currently that's using ruby acorn which was added in wrath and why missing in TBC, so finding an item that existed in TBC is a good find.
