### ISSUE TITLE
Support Libsharemedia for Victory Sound missing

### ISSUE THREAD

**Issue by neodata83** [DeadlyBossMods/DBM-TBC-Classic#109]
I cant choose my Sounds from sharemedia addon in the Victory Sounds/Wipe Sound. Or is this a intended ?

**Comment by QartemisT** [comment]
Hi there and apologies for the late reply.

Yes, this is an intended behavour, you should use the registration method for DBM to register these sounds.

Simply call;
`DBM:AddVictorySound(text, value, length)`
`DBM:AddDefeatSound(text, value, length)`

- Text is the display name that would appear in the dropdown
- Value is the location to the sound file
- Length is the length in seconds that it lasts

**Comment by MysticalOS** [comment]
Just to reiterate further, reason the tables aren't just populated with all LSM sounds, is because event sounds are sounds that actually make sense for event. populating that menu with a bunch of random ticks and meows and horns etc would just not make sense, so DBM populates that menu exclusive of LSM
