### ISSUE TITLE
Gruul Layer / Kara

### ISSUE THREAD

**Issue by CorDHawk** [DeadlyBossMods/DBM-TBC-Classic#29]
**Describe the bug**
1. We have been raiding in Gruul and the raid warnings often do not reflect the actual spell Gruul or timing of the spell. 
E.g. Reverberation and Ground Slam are called and given timer, yet when they timer goes off the spells do not.

2. In Kara we have a different issue on Nightbane.
E.g. Nightbane - Smoking Blast does not call out intended target <- not sure if bug or if that is how its intended

**To Reproduce**
1. Raid in Kara or Gruul
2. Wait for one of the above spells to be called by DBM
3. See if timer or call was correct

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No, but experienced by all of raid using DBM.

**Which version of DeadlyBossMods are you using?**
2.5.7-bcc
**Was it working in a previous version? If yes, which was the last good one?**
No
**Additional context**
We have been noticing these inconsistencies for the last few weeks of raiding

**Comment by MysticalOS** [comment]
https://classic.warcraftlogs.com/reports/vChDqxbZtfzF9dQw#fight=9&view=events&pins=2%24Off%24%23244F4B%24expression%24(ability.id%20%3D%2033525%20or%20ability.id%20%3D%2033654)%20and%20type%20%3D%20%22begincast%22%20%20or%20ability.id%20%3D%2036297%20and%20type%20%3D%20%22cast%22%20%20or%20ability.id%20%3D%2036300

This log alone shows a variation of 75-95 on ground slam, and that was literally the first log i opened at random. the variation is probably even larger.

Maiden has same problem. there is nothing wrong with timers, the fights are just designed to have wildly variable timers and are all DBM COOLDOWN timers.

when you see a timer with a "~" or letters "CD" in it, it means it's a cooldown timer and not a next cast timer. These are imprecise because it's not possible to be precise and should only be used to indicate when a spell will NOT be cast, not when it will be cast.

I have no idea what Smoking Blast is, but it doesn't look like a feature of nightbane mod at all.

**Comment by CorDHawk** [comment]
Thank you @MysticalOS for reaching out! I read the commit about Maiden so that totally makes sense that it is the same thing for Ground slam. We can try and find reference to when those specific variations are.

Looking into Nightbane.lua I am also not seeing reference directly to Smoking Blast. 
https://wowwiki-archive.fandom.com/wiki/Nightbane_(boss) <-- Nightbane facts

In the above reference about Nightbane he has specials spells when in Air mode. 
Rain of Bones, Smoking Blast, and Fireball Barrage
Smoking Blast is a powerful spell that is just crushing our healers as we cannot figure out who it is targeting quickly. Is it possible DBM will add support for Smoking Blast in the future? Even better if it calls out who is the target.

Much Thanks!

**Comment by MysticalOS** [comment]
Nightbane request added to alpha and other stuff is not broken so closing this
