### ISSUE TITLE
Vashj bug: "Tainted Core on You"

### ISSUE THREAD

**Issue by Jakobud** [DeadlyBossMods/DBM-TBC-Classic#73]
Throughout Vashj Phase 2, sometimes DBM puts the words "Tainted Core on You" in the middle of your screen even though no one threw the core to you.

It should only say "Tainted Core on You" if someone threw the core to you.

**Do you have an error log of what happened?**
No errors reported

**To Reproduce**
1. Get to Vashj phase 2
2. Wait until someone throws a core to someone else
3. You will see the message on your screen even if the core was not thrown to you

**Which version of DeadlyBossMods are you using?**
DBM-2.5.15-1b8cddc0-bcc

**Was it working in a previous version? If yes, which was the last good one?**
I don't know

**Comment by MysticalOS** [comment]
in latest alpha all core announcements were removed from mod. taht was a feature that worked fine on retail/OG TBC, but desn't work in TBC classic do to changes somewhere I can't verify. Because of that I just had to kill it off. It's possible to fix it but only with logs I do not have so for immediate term the feature is now gone so it causes less confusion.

Closing issue since it is resolved in alpha already.
